
-- PROACT1102 V2 upgrade
-- Adds user roles, manager/admin access, corrective actions and supporting RLS.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'employee' check (role in ('employee','manager','admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'employee')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.profiles (id, role)
select id, 'employee' from auth.users
on conflict (id) do nothing;

create or replace function public.is_manager_or_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role in ('manager','admin')
  );
$$;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles
for select
using (id = auth.uid() or public.is_manager_or_admin());

drop policy if exists "Users can view own reports" on public.reports;
create policy "Users can view own reports or managers view all"
on public.reports
for select
using (auth.uid() = user_id or public.is_manager_or_admin());

drop policy if exists "Users can insert own reports" on public.reports;
create policy "Users can insert own reports"
on public.reports
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update own reports" on public.reports;
drop policy if exists "Managers can update reports" on public.reports;
create policy "Users update own reports or managers update all"
on public.reports
for update
using (auth.uid() = user_id or public.is_manager_or_admin())
with check (auth.uid() = user_id or public.is_manager_or_admin());

create table if not exists public.actions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  report_id bigint not null references public.reports(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  action_text text not null,
  assigned_to text,
  priority text not null default 'Medium',
  due_date date,
  status text not null default 'Open'
);

alter table public.actions enable row level security;

drop policy if exists "Managers can view actions" on public.actions;
create policy "Managers can view actions"
on public.actions
for select
using (public.is_manager_or_admin());

drop policy if exists "Managers can create actions" on public.actions;
create policy "Managers can create actions"
on public.actions
for insert
with check (public.is_manager_or_admin() and auth.uid() = created_by);

drop policy if exists "Managers can update actions" on public.actions;
create policy "Managers can update actions"
on public.actions
for update
using (public.is_manager_or_admin())
with check (public.is_manager_or_admin());

-- IMPORTANT:
-- New users default to employee.
-- To make your own demo account a manager:
-- 1. Open Authentication > Users in Supabase.
-- 2. Copy your user UUID.
-- 3. Run:
-- update public.profiles set role = 'manager' where id = 'PASTE-USER-UUID-HERE';
